name: CI

on:
  push:
    branches: master
  pull_request:
    branches: master
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 3 * * 6'
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason'
        required: false
        default: 'Manual trigger'

jobs:
  Tests:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
          python-version: [3.6, 3.7, 3.8]
          requirements-level: [min, pypi]
          db-service: [postgresql9]

          exclude:
          - python-version: 3.8
            requirements-level: min

          include:
          - db-service: postgresql9
            DB: postgresql
            POSTGRESQL_VERSION: POSTGRESQL_9_LATEST
            SQLALCHEMY_DATABASE_URI: "postgresql+psycopg2://invenio:invenio@localhost:5432/invenio"
            EXTRAS: "all,postgresql"

    env:
      SQLALCHEMY_DATABASE_URI: ${{matrix.SQLALCHEMY_DATABASE_URI}}
      POSTGRESQL_VERSION: ${{matrix.POSTGRESQL_VERSION}}
      DB: ${{ matrix.DB }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Generate dependencies
        run: |
          pip uninstall -y six
          python -m pip install --upgrade pip setuptools py wheel requirements-builder
          requirements-builder -e ${{ matrix.EXTRAS }} ${{ matrix.requirements-file }} --level=${{ matrix.requirements-level }} setup.py > .${{ matrix.requirements-level }}-${{ matrix.python-version }}-requirements.txt

      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('.${{ matrix.requirements-level }}-${{ matrix.python-version }}-requirements.txt') }}

      - name: Install dependencies
        run: |
          pip install -r .${{matrix.requirements-level}}-${{ matrix.python-version }}-requirements.txt
          pip install .[${{ matrix.EXTRAS }}]
          pip freeze

      - name: Run tests
        run: |
          ./run-tests.sh
